import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'dark:bg-zinc-700',
    'dark:bg-slate-700',
    'dark:bg-neutral-700',
    'dark:bg-gray-700',
    'dark:bg-stone-700',
    'dark:bg-yellow-700',
    'dark:bg-orange-700',
    'dark:bg-violet-700',
    'dark:bg-blue-700',
    'dark:bg-sky-700',
    'dark:bg-indigo-700',
    'dark:bg-fuchsia-700',
    'dark:bg-pink-700',
    'dark:bg-rose-700',
    'dark:bg-purple-700',
    'dark:bg-cyan-700',
    'dark:bg-teal-700',
    'dark:bg-emerald-700',
    'dark:bg-lime-700',
    'dark:bg-green-700',
    'dark:bg-amber-700',
    'bg-zinc-200',
    'bg-slate-200',
    'bg-neutral-200',
    'bg-gray-200',
    'bg-stone-200',
    'bg-yellow-200',
    'bg-orange-200',
    'bg-violet-200',
    'bg-blue-200',
    'bg-sky-200',
    'bg-indigo-200',
    'bg-fuchsia-200',
    'bg-pink-200',
    'bg-rose-200',
    'bg-purple-200',
    'bg-cyan-200',
    'bg-teal-200',
    'bg-emerald-200',
    'bg-lime-200',
    'bg-green-200',
    'bg-amber-200',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: 'hsl(var(--foreground))',
            a: {
              color: 'hsl(var(--primary))',
              '&:hover': {
                color: 'hsl(var(--primary))',
              },
            },
          },
        },
      },
    },
  },

  // plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
} satisfies Config;
